drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);  // 테이블생성

insert into member(name) values('spring')   // 데이터 추가

